version: '3.6'
# docker-compose -f docker-compose-cluster.yml up -d --scale dnode=2
# docker system prune --volumes
services:
  bootstrap:
    image: store/marklogicdb/marklogic-server:10.0-7-dev-centos
    container_name: bootstrap
    domainname: .
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - TZ=America/New_York
    ports:
      - 7997-8070:7997-8070
    networks:
      - external_net
      - internal_net
    volumes:
      - type: volume
        target: /var/opt/MarkLogic

  dnode:
    image: store/marklogicdb/marklogic-server:10.0-7-dev-centos
    domainname: .
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - MARKLOGIC_JOIN_CLUSTER=true
      - TZ=America/New_York
    depends_on:
      - bootstrap
    networks:
      - internal_net

networks:
  external_net: {}
  internal_net:
    internal: true
