version: '3.6'
# docker-compose -f docker-compose-cluster.yml up -d --scale dnode=2
# docker system prune --volumes
services:
  bootstrap:
    image: "${IMAGE}"
    container_name: bootstrap
    hostname: ml-node-a.local
    #domainname: local
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - TZ=America/New_York
    ports:
      - 7997-8070:7997-8070
    networks:
      - external_net
      - internal_net
    volumes:
      - type: volume
        target: /var/opt/MarkLogic

  dnode1:
    image: "${IMAGE}"
    #domainname: local
    hostname: ml-node-b.local
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - MARKLOGIC_JOIN_CLUSTER=true
      - TZ=America/New_York
    depends_on:
      - bootstrap
    networks:
      - internal_net

  dnode2:
    image: "${IMAGE}"
    #domainname: local
    hostname: ml-node-c.local
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - MARKLOGIC_JOIN_CLUSTER=true
      - TZ=America/New_York
    depends_on:
      - bootstrap
    networks:
      - internal_net

networks:
  external_net: {}
  internal_net:
    internal: true
