version: '3.6'
services:
  bootstrap:
    image: "${IMAGE_CLUSTER}"
    container_name: bootstrap
    hostname: ml-node-a.local
    restart: always
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - TZ=America/New_York
    ports:
      - 7997-8070:7997-8070
    networks:
      - external_net
      - internal_net
    volumes:
      - type: volume
        target: /var/opt/MarkLogic

  dnode1:
    image: "${IMAGE_CLUSTER}"
    hostname: ml-node-b.local
    restart: always
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - MARKLOGIC_JOIN_CLUSTER=true
      - MARKLOGIC_BOOTSTRAP_HOST=ml-node-a.local
      - TZ=America/New_York
    depends_on:
      - bootstrap
    networks:
      - internal_net

  dnode2:
    image: "${IMAGE_CLUSTER}"
    hostname: ml-node-c.local
    restart: always
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - MARKLOGIC_JOIN_CLUSTER=true
      - MARKLOGIC_BOOTSTRAP_HOST=ml-node-a.local
      - TZ=America/New_York
    depends_on:
      - bootstrap
    networks:
      - internal_net

networks:
  external_net: {}
  internal_net:
    internal: true
