version: '3.6'
services:
  bootstrap:
    image: "${IMAGE_CLUSTER}"
    container_name: bootstrap
    hostname: d-node-1.local
    restart: always
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - TZ=America/New_York
    ports:
      - 7997-8070:7997-8070
    networks:
      - internal_net
      - external_net
    volumes:
      - type: volume
        target: /var/opt/MarkLogic

  dnode2:
    image: "${IMAGE_CLUSTER}"
    hostname: d-node-2.local
    restart: always
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - MARKLOGIC_JOIN_CLUSTER=true
      - TZ=America/New_York
    depends_on:
      - bootstrap
    networks:
      - internal_net

  dnode3:
    image: "${IMAGE_CLUSTER}"
    hostname: d-node-3.local
    restart: always
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - MARKLOGIC_JOIN_CLUSTER=true
      - TZ=America/New_York
    depends_on:
      - bootstrap
    networks:
      - internal_net

  enode1:
    image: "${IMAGE_CLUSTER}"
    hostname: e-node-1.local
    restart: always
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - MARKLOGIC_JOIN_CLUSTER=true
      - TZ=America/New_York
    ports:
      - 8997-9070:7997-8070
    networks:
      - internal_net
      - external_net

  enode2:
    image: "${IMAGE_CLUSTER}"
    hostname: e-node-2.local
    restart: always
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - MARKLOGIC_JOIN_CLUSTER=true
      - TZ=America/New_York
    networks:
      - internal_net

  enode3:
    image: "${IMAGE_CLUSTER}"
    hostname: e-node-3.local
    restart: always
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - MARKLOGIC_JOIN_CLUSTER=true
      - TZ=America/New_York
    networks:
      - internal_net
  enode4:
    image: "${IMAGE_CLUSTER}"
    hostname: e-node-4.local
    restart: always
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - MARKLOGIC_JOIN_CLUSTER=true
      - TZ=America/New_York
    networks:
      - internal_net

  enode5:
    image: "${IMAGE_CLUSTER}"
    hostname: e-node-5.local
    restart: always
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - MARKLOGIC_JOIN_CLUSTER=true
      - TZ=America/New_York
    networks:
      - internal_net

  enode6:
    image: "${IMAGE_CLUSTER}"
    hostname: e-node-6.local
    restart: always
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - MARKLOGIC_JOIN_CLUSTER=true
      - TZ=America/New_York
    networks:
      - internal_net
networks:
  external_net: {}
  internal_net:
    internal: true
